// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import RegisterController from "./register_controller"
application.register("register", RegisterController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
